#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployments
  name: barramento-de-eventos-deployment
spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
      #rótulo, app não tem nada de especial, pode ser qq coisa
      #Deployment vai selecionar todo Pod que tiver esse rótulo
      app: barramento-de-eventos
  #modelo a ser usado para construçao dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim,
        #serão selecionados por esse deployment
        app: barramento-de-eventos
    spec:
      containers:
        - name: lembretes
          image: lucasmilani/barramento-de-eventos
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: barramento-de-eventos-service
spec:
  type: ClusterIP
  selector:
    app: barramento-de-eventos
  ports:
    - name: barramento-de-eventos
      protocol: TCP
      port: 10000
      targetPort: 10000
